$engine: 3
name: PlumeESX
version: 2.0.0
author: Tabarra & Chip
description: A full featured (13 jobs) and highly configurable yet lightweight ESX v1-final base that can be easily extended. 

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: f559e8bbb7a5c1ee8db1d26ed2cf7d29fa59e146
    subpath: resources
    dest: ./resources
  
  # Download and prepare server.cfg / loadingscreen / database
  - action: download_github
    src: https://github.com/tabarra/PlumeESX-recipe
    ref: main
    dest: ./tmp/plume_esx

  - action: move_path
    src: ./tmp/plume_esx/server.cfg
    dest: ./server.cfg
  
  - action: move_path
    src: ./tmp/plume_esx/loadingscreen
    dest: ./resources/loadingscreen

  - action: connect_database
  - action: query_database
    file: ./tmp/plume_esx/plume.sql
  - action: query_database
    file: ./tmp/plume_esx/gcphone.sql

  # Download basic resources and ESX dependencies
  - action: download_github
    src: https://github.com/Blumlaut/EasyAdmin
    ref: 4a2c04c44b4c4a3084a5641e82d61632faa8b913
    dest: ./resources/EasyAdmin

  - action: download_github
    src: https://github.com/esx-framework/async
    ref: e7b778f0c7236132596e98d8ebd33e1127dbb4c4
    dest: ./resources/async

  - action: download_github
    src: https://github.com/brouznouf/fivem-mysql-async
    ref: c5fa317a65acfe2eef453257e19e3b4fde137089
    dest: ./resources/mysql-async

  - action: download_github
    src: https://github.com/esx-framework/cron
    ref: 89914888d7dd801fb8430aeb386fd423e0f86f46
    dest: ./resources/cron

  - action: download_github
    src: https://github.com/esx-framework/instance
    ref: 56295645638474a8780d3a2c2da356c28032ba3f
    dest: ./resources/instance

  - action: download_github
    src: https://github.com/esx-framework/skinchanger
    ref: d716177f226ad696d903a27d7afa3ca97ce80a3b
    dest: ./resources/skinchanger

  - action: download_github
    src: https://github.com/HypeLevels/simpledrift
    ref: 77e378a2b59fcaca7624cb51575b2a3d39e3b635
    dest: ./resources/simpledrift

  - action: download_github
    src: https://github.com/dsheedes/cd_easytime
    ref: 50bb4ccb3ad3c1abe56c1a46aa7827fc250d6f1e
    dest: ./resources/cd_easytime

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: 4ae8aaefd38238e72ff8f36417decb05064cb924
    dest: ./resources/bob74_ipl

  - action: download_github
    src: https://github.com/ali-exacute/esx_adminplus
    ref: 08dc5d7bdc95a031a718c38845afa10b239ec753
    dest: ./resources/esx_adminplus

  # Download ESX resources
  - action: download_github
    src: https://github.com/esx-framework/es_extended
    ref: legacy
    dest: ./resources/[esx]/es_extended

  - action: download_github
    src: https://github.com/esx-framework/esx_menu_default
    ref: 2d46087ade9369c46df1d80b706dc13e6e4ac673
    dest: ./resources/[esx]/esx_menu_default

  - action: download_github
    src: https://github.com/esx-framework/esx_menu_dialog
    ref: 1f53d642aa5867fd7762e1c98454d616e2a66f6a
    dest: ./resources/[esx]/esx_menu_dialog

  - action: download_github
    src: https://github.com/esx-framework/esx_menu_list
    ref: c4c88a9afd475074213d2586d09ac091c389c369
    dest: ./resources/[esx]/esx_menu_list

  - action: download_github
    src: https://github.com/esx-framework/esx_datastore
    ref: dfe0321bdd7ba35b6ec3316529c220b827816997
    dest: ./resources/[esx]/esx_datastore

  - action: download_github
    src: https://github.com/esx-framework/esx_identity
    ref: a74f91e7f90c3cc82da854637bb9b4611f52e810
    dest: ./resources/[esx]/esx_identity

  - action: download_github
    src: https://github.com/esx-framework/esx_skin
    ref: b98f29022a32548f2104585ee1a0c68f882a8248
    dest: ./resources/[esx]/esx_skin

  - action: download_github
    src: https://github.com/esx-framework/esx_status
    ref: 3d526522fa78c37b5967005d19106eadd27695f1
    dest: ./resources/[esx]/esx_status

  - action: download_github
    src: https://github.com/esx-framework/esx_basicneeds
    ref: dcde28674724f65864dbeb7abe2978981bf0b17c
    dest: ./resources/[esx]/esx_basicneeds

  - action: download_github
    src: https://github.com/esx-framework/esx_billing
    ref: 18df79337a5d35b945fa1ecfa2794e6bee3407aa
    dest: ./resources/[esx]/esx_billing

  - action: download_github
    src: https://github.com/esx-framework/esx_addoninventory
    ref: 5709570bc2cda27e08159536e3a6c9d1a3734915
    dest: ./resources/[esx]/esx_addoninventory

  - action: download_github
    src: https://github.com/esx-framework/esx_addonaccount
    ref: 3573919be24068283a3103a08414f64398381513
    dest: ./resources/[esx]/esx_addonaccount

  - action: download_github
    src: https://github.com/esx-framework/esx_society
    ref: b033466e14cfed43742117b11f1526b2e127e241
    dest: ./resources/[esx]/esx_society

  - action: download_github
    src: https://github.com/esx-framework/esx_license
    ref: 4a791b81827f17f7e31aeac1fb15f3c9c9ec6764
    dest: ./resources/[esx]/esx_license

  - action: download_github
    src: https://github.com/esx-framework/esx_service
    ref: 0c85c4e4b212015fbf97a4707ad59aa55904768d
    dest: ./resources/[esx]/esx_service

  - action: download_github
    src: https://github.com/esx-framework/esx_garage
    ref: 6ae703b18965452d148541c061f830469c8a8bd9
    dest: ./resources/[esx]/esx_garage

  - action: download_github
    src: https://github.com/esx-framework/esx_vehicleshop
    ref: 48d1d8fbeb89c491c7796e16af20e5226e1cfa8b
    dest: ./resources/[esx]/esx_vehicleshop

  - action: download_github
    src: https://github.com/esx-framework/esx_jobs
    ref: fb6bd5ef72cff371a7ff2b46526cbc5708b2c3ad
    dest: ./resources/[esx]/esx_jobs

  - action: download_github
    src: https://github.com/esx-framework/esx_joblisting
    ref: bbce9722a24269e667d00cc26b7c6408f29cdfb7
    dest: ./resources/[esx]/esx_joblisting

  - action: download_github
    src: https://github.com/esx-framework/esx_policejob
    ref: 22cdd4ef2d7808ae8109d1e9f65a336300f2cad2
    dest: ./resources/[esx]/esx_policejob

  - action: download_github
    src: https://github.com/esx-framework/esx_ambulancejob
    ref: ba0961095c8a31f1d993c2c13f913dbb37bf52bf
    dest: ./resources/[esx]/esx_ambulancejob

  - action: download_github
    src: https://github.com/esx-framework/esx_mechanicjob
    ref: d0e414fc96d3a07a68cafd57aaff954baa28bf99
    dest: ./resources/[esx]/esx_mechanicjob

  - action: download_github
    src: https://github.com/esx-framework/esx_taxijob
    ref: 0f69bfce0a8f587abcfc7e9567fffd3fa53e663c
    dest: ./resources/[esx]/esx_taxijob

  - action: download_github
    src: https://github.com/esx-framework/esx_lscustom
    ref: b6f2f129ababf6ac3709145c814f52453d6b7ffa
    dest: ./resources/[esx]/esx_lscustom

  - action: download_github
    src: https://github.com/esx-framework/esx_atm
    ref: e2d7eead18284052e5732856bf93a4b439764c61
    dest: ./resources/[esx]/esx_atm 

  - action: download_github
    src: https://github.com/esx-framework/esx_shops
    ref: d8715d347c874905813446bfe2b810e63f19681b
    dest: ./resources/[esx]/esx_shops

  - action: download_github
    src: https://github.com/esx-framework/esx_weaponshop
    ref: b42afd53e3f9876c357962a9d79d86dc6919fde0
    dest: ./resources/[esx]/esx_weaponshop

  - action: download_github
    src: https://github.com/esx-framework/esx_clotheshop
    ref: 04183ae7c0a9c1505b37a13bb4e2bbd195862511
    dest: ./resources/[esx]/esx_clotheshop

  - action: download_github
    src: https://github.com/esx-framework/esx_barbershop
    ref: 25103f725db46a22ff8e12925290f2b71e9137cc
    dest: ./resources/[esx]/esx_barbershop

  - action: download_github
    src: https://github.com/esx-framework/esx_drugs
    ref: 5d80d30de3d62122c1a8144fe0fc8635da14e6b0
    dest: ./resources/[esx]/esx_drugs

  - action: download_github
    src: https://github.com/esx-framework/esx_holdup
    ref: ee9c916ebf955abefa3bfdbd20a773122b865a22
    dest: ./resources/[esx]/esx_holdup

  ## GCPhone stuff
  - action: download_file
    url: https://github.com/Re-Ignited-Development/Re-Ignited-Phone/releases/download/V1.5/resources-1.2.zip
    path: ./tmp/gcphone.zip
  - action: unzip
    src: ./tmp/gcphone.zip
    dest: ./tmp
  - action: move_path
    src: ./tmp/resources-1.2/gcphone
    dest: ./resources/gcphone
  
  ##PMA-Voice
  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: 6f3f52616746aebb4a13d313ef3bb7ced7818b5d
    dest: ./resources/pma-voice

  - action: replace_string
    file: ./resources/gcphone/config.lua
    search: 'Config.UseMumbleVoIP = false'
    replace: 'Config.UseMumbleVoIP = true'



  ## KL HUD v2
  - action: download_github
    src: https://github.com/Kilichi/Kl_HudV2
    ref: ac8a321ff335706509bdc6122a2984a80082e669
    dest: ./resources/Kl_HudV2

  - action: replace_string
    file: ./resources/[esx]/esx_status/client/main.lua
    search: 'esx_status:onTick'
    replace: 'Kl_Hud:onTick'


  ## Final touches
  - action: replace_string
    mode: all_vars
    file: ./resources/loadingscreen/config.js
    
  - action: remove_path
    path: ./tmp
